import {test} from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const core=await import(process.env.MEAL_CORE_MODULE?pathToFileURL(process.env.MEAL_CORE_MODULE).href:'../preview/core.mjs');
const food=(changes={})=>({id:'food1',name:'米饭',grams:150,kcal:175,fraction:1,protein:3,fat:1,carbs:38,...changes});
const meal=(changes={})=>({id:'meal1',kind:'午餐',date:'2026-10-01T12:00:00+08:00',foods:[food()],version:1,...changes});
test('consumed half changes actual calories and meal total',()=>{assert.equal(core.effectiveKcal(food({fraction:.5})),87.5);assert.equal(core.totalKcal([food({fraction:.5}),food({id:'f2',kcal:240})]),327.5)});
test('zero consumption is valid and remains zero',()=>assert.equal(core.totalKcal([food({fraction:0})]),0));
test('negative and above-one fractions are rejected',()=>{assert.throws(()=>core.validateFood(food({fraction:-.1})));assert.throws(()=>core.validateFood(food({fraction:1.1})))});
test('non finite quantities and kcal are rejected',()=>{for(const v of [NaN,Infinity,-Infinity]){assert.throws(()=>core.validateFood(food({grams:v})));assert.throws(()=>core.validateFood(food({kcal:v})))}});
test('zero negative and too-large grams are rejected',()=>{for(const v of [0,-1,10001])assert.throws(()=>core.validateFood(food({grams:v})))});
test('zero kcal is allowed but negative kcal is rejected',()=>{core.validateFood(food({kcal:0}));assert.throws(()=>core.validateFood(food({kcal:-1})))});
test('empty name and oversized name are rejected',()=>{assert.throws(()=>core.validateFood(food({name:' '})));assert.throws(()=>core.validateFood(food({name:'饭'.repeat(81)})))});
test('unknown nutrients stay unknown',()=>assert.equal(core.totalNutrient([food(),food({protein:null})],'protein'),null));
test('known nutrients follow actual consumption',()=>assert.equal(core.totalNutrient([food({fraction:.5})],'protein'),1.5));
test('empty meal and invalid kind cannot be saved',()=>{assert.throws(()=>core.validateMeal(meal({foods:[]})));assert.throws(()=>core.validateMeal(meal({kind:'未知'})))});
test('duplicate food identity is rejected',()=>assert.throws(()=>core.validateMeal(meal({foods:[food(),food()]}))));
test('more than thirty foods are rejected',()=>assert.throws(()=>core.validateMeal(meal({foods:Array.from({length:31},(_,i)=>food({id:`f${i}`}))}))));
test('repeated save updates one identity and increments version',()=>{let list=core.upsert([],meal());list=core.upsert(list,meal({foods:[food({fraction:.5})]}));assert.equal(list.length,1);assert.equal(list[0].version,2);assert.equal(core.totalKcal(list[0].foods),87.5)});
test('preview never claims real health sync',()=>assert.equal(core.upsert([],meal({healthStatus:'synced'}))[0].healthStatus,'unavailable'));
test('date selection follows local calendar day',()=>{const date=new Date(2026,9,1,23,30);assert.equal(core.localDay(date),'2026-10-01');assert.equal(core.mealsOn([meal({date:date.toISOString()})],date).length,1)});
test('invalid dates are rejected',()=>assert.throws(()=>core.localDay('invalid')));
test('missing date is not silently replaced with today',()=>assert.throws(()=>core.validateMeal(meal({date:undefined}))));
test('trend only contains dates with actual meals',()=>{const entries=core.aggregate([meal()],new Date('2026-09-30'),new Date('2026-10-02'));assert.equal(entries.length,1);assert.equal(entries[0].kcal,175)});
test('out-of-range meal is excluded from trend',()=>assert.equal(core.aggregate([meal()],new Date('2026-11-01'),new Date('2026-11-02')).length,0));
test('model JSON and one markdown fence can be parsed',()=>{const text=JSON.stringify({foods:[{name:'饭',grams:100,kcal:120,protein:null}]});assert.equal(core.parseRecognition(text)[0].kcal,120);assert.equal(core.parseRecognition('```json\n'+text+'\n```')[0].fraction,1)});
test('invalid model payload does not become a successful meal',()=>{assert.throws(()=>core.parseRecognition('{"foods":[]}'));assert.throws(()=>core.parseRecognition('模型失败'));assert.throws(()=>core.parseRecognition('{"foods":[{"name":"饭","grams":-1,"kcal":5}]}'))});
test('export and restore preserve identities and actual consumption',()=>{const m=meal({foods:[food({fraction:.5})]});assert.deepEqual(core.restore(core.exportMeals([m])),[m])});
test('corrupt schema and duplicate records are rejected',()=>{assert.throws(()=>core.restore('{"schemaVersion":2,"meals":[]}'));assert.throws(()=>core.restore(JSON.stringify({schemaVersion:1,meals:[meal(),meal()]})))});
test('copy text uses consumed fraction and marks estimates',()=>{const text=core.copyText(meal({foods:[food({fraction:.5})]}));assert.match(text,/75克/);assert.match(text,/88千卡/);assert.match(text,/估算/)});
